name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: push

env:
  DAY_OF_WEEK: Monday
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: "Say Hello Mona it's Monday"
        run: echo "$First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
